[package]
name = "isl"
version = "0.1.0"
authors = ["MashPlant <740678788@qq.com>"]
edition = "2018"

[dependencies]
tools = { git = "https://github.com/MashPlant/tools", features = ["debug-panic"] }
libc = "0.2"
